import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common'; import { PrismaService } from '../prisma/prisma.service'; import * as path from 'path'; import * as unzipper from 'unzipper';
const ignored=new Set(['node_modules','.git','.next','dist','build','coverage']); const allowed=new Set(['.ts','.tsx','.js','.jsx','.json','.css','.scss','.html','.md','.py','.java','.c','.cpp','.h','.hpp','.go','.rs','.php','.rb','.sql','.yaml','.yml','.env.example']);
@Injectable() export class ProjectsService {constructor(private db:PrismaService){}
 async create(userId:string,name:string,description=''){if(!name?.trim())throw new BadRequestException('Project name is required');return this.db.project.create({data:{userId,name:name.trim(),description}})}
 async list(userId:string){return this.db.project.findMany({where:{userId},orderBy:{createdAt:'desc'},include:{_count:{select:{files:true,reviews:true}}})}
 async get(userId:string,id:string){const p=await this.db.project.findFirst({where:{id,userId},include:{files:{select:{id,path,name,content,size,mimeType,createdAt},orderBy:{path:'asc'}}}});if(!p)throw new NotFoundException('Project not found');return p}
 async delete(userId:string,id:string){return this.db.project.deleteMany({where:{id,userId}})}
 async upload(userId:string,id:string,file:Express.Multer.File){await this.get(userId,id); if(!file?.originalname.toLowerCase().endsWith('.zip'))throw new BadRequestException('Only ZIP files are supported'); const dir=await unzipper.Open.buffer(file.buffer); const rows:any[]=[]; for(const e of dir.files){const normalized=path.posix.normalize(e.path.replaceAll('\\','/')); if(normalized.startsWith('../')||normalized.includes('/../')||normalized.startsWith('/'))continue; const parts=normalized.split('/'); if(parts.some(x=>ignored.has(x)))continue; if(e.type==='File'&&allowed.has(path.posix.extname(normalized).toLowerCase())){const buf=await e.buffer(); if(buf.length>500000)continue; const content=buf.toString('utf8'); rows.push({projectId:id,path:normalized,name:path.posix.basename(normalized),content,size:buf.length,mimeType:'text/plain'});}}
 await this.db.file.deleteMany({where:{projectId:id}}); if(rows.length)await this.db.file.createMany({data:rows,skipDuplicates:true}); return {count:rows.length}; }
 async file(userId:string,projectId:string,fileId:string){await this.get(userId,projectId);const f=await this.db.file.findFirst({where:{id:fileId,projectId}});if(!f)throw new NotFoundException('File not found');return f}
}
